In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
file ='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스  = pd.read_csv(file)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [5]:
incode = pd.get_dummies(아이리스)
incode.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
독립 = incode[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = incode[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [12]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')
 

In [14]:
model.fit(독립, 종속, epochs=5000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0606 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0606 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0605 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0604 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0608 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0604 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0608 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0608 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0606 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0604 - accuracy: 0.9800


In [15]:
print(model.predict(독립[:5]))
print(종속[:5])
 

[[1.0000000e+00 2.5735518e-09 1.7169602e-20]
 [9.9999988e-01 1.0953273e-07 7.0184472e-18]
 [1.0000000e+00 1.7272054e-08 5.5897030e-19]
 [9.9999976e-01 2.6285355e-07 3.4413288e-17]
 [1.0000000e+00 1.6223264e-09 9.4203391e-21]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [16]:
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.0989720e-18 7.6713543e-03 9.9232870e-01]
 [2.2385653e-17 2.8434308e-02 9.7156572e-01]
 [1.0195175e-16 5.2773852e-02 9.4722611e-01]
 [5.5366957e-19 4.7638421e-03 9.9523622e-01]
 [1.0406392e-15 9.8786704e-02 9.0121329e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [17]:
print(model.get_weights())

[array([[  3.3842702 ,   1.3216838 ,  -0.91830176],
       [  8.091094  ,   1.4142563 ,  -2.2141864 ],
       [-10.458648  ,  -1.215823  ,   2.83792   ],
       [-13.919735  ,  -3.8726566 ,   4.2041335 ]], dtype=float32), array([ 5.2034516,  4.364223 , -4.5360646], dtype=float32)]
